### ISSUE TITLE
page principale du jeu solo

### ISSUE THREAD

**Issue by kubraArs** [e-vinci/web2-2022-project-group-09#17]

**Comment by kubraArs** [comment]
Commits on Nov 28, 2022


![Image](https://user-images.githubusercontent.com/95171219/205463778-ba3076fc-38ae-43e4-b008-f06194ee21c5.png)

**Comment by leonkelmendi1** [comment]
![Image](https://user-images.githubusercontent.com/83784260/205506860-826de323-7644-4de8-8242-07f50b3ca644.png)

Commits on Dec 2, 2022
