### ISSUE TITLE
ajouter le "victoire"

### ISSUE THREAD

**Issue by kubraArs** [e-vinci/web2-2022-project-group-09#22]

**Comment by leonkelmendi1** [comment]
![Image](https://user-images.githubusercontent.com/83784260/206924969-95a2fb7b-c29e-4752-bd13-13a65dcc7861.png)

**Comment by leonkelmendi1** [comment]
![Image](https://user-images.githubusercontent.com/83784260/206924987-5228f3d6-ae3d-4e4b-890f-45ac34538e34.png)
